package autodrillnext.model;

public enum DiagnosticCode {
    UNSUPPORTED_CONTENT,
    NO_UNLOCKED_CONTENT,
    TERRAIN_OR_RULE_BLOCKED,
    BUDGET_DEFICIT,
    SAFETY_POLICY_DENIED,
    NO_VALID_SINK,
    ORE_NOT_FOUND,
    NO_DRILL_CANDIDATE,
    NO_UNLOCKED_TRANSPORT,
    NO_ROUTE,
    NO_POWER_SOURCE,
    NO_LIQUID_SOURCE,
    NO_POWER_SUPPORT,
    NO_LIQUID_SUPPORT,
    DEPENDENCY_OVER_BUDGET,
    EXISTING_NETWORK_BLOCKED,
    STALE_SNAPSHOT,
    PARTIAL_PLAN,
    SEARCH_LIMIT_REACHED,
    NO_FEASIBLE_PLAN
}
